olenaza_hw_project:
    resource: "@OlenazaHWProjectBundle/Resources/config/routing_projects.yml"

olenaza_hw_project_authors:
    resource: "@OlenazaHWProjectBundle/Resources/config/routing_authors.yml"
    prefix: /authors


